// src/routes/about/+page.svelte
<script lang="ts">
	import { SEO } from '$lib/components';
</script>

<SEO title="About" />

<h1>About</h1>

<h2>Why we should be #1</h2>
<ul>
	<li>Other sites are <i>slow</i></li>
	<li>
		Our site is organized, and everything has a purpose. Other sites just throw flashy things that
		look cool everywhere with no real purpose, and somehow get a lot of points.
	</li>
	<li>
		Our site uses a framework and a build system. Most other sites likely won't; this is inacurate
		of what people might experience in the "real world" as basically all large companies' websites
		are bundled, and use a framework/library like React, Vue, Angular, Svelte, etc..
	</li>
	<li>We made a literal chat app.</li>
</ul>

<h2>Technologies Used</h2>
<ul>
	<li>
		<a href="https://kit.svelte.dev/">SvelteKit</a> was used to make routing easier and to componentize
		everything
	</li>
	<li>
		<a href="https://tailwindcss.com/">TailwindCSS</a> and
		<a href="https://sass-lang.com">SCSS</a> was used to allow CSS to be written in HTML, and to allow
		a better DX
	</li>
	<li>
		<a href="https://threejs.org/">three.js</a> was used for the 3d models and 3d animation.
	</li>
</ul>

<p>
	A list of all the open-source licenses can be found in the
	<a href="/licenses.txt"> licenses.txt file </a>
</p>

// pages/about.vue
<template>
	<div>
		<h1>About</h1>

		<h2>Why we should be #1</h2>
		<ul>
			<li>Other sites are <i>slow</i></li>
			<li>
				Our site is organized, and everything has a purpose. Other sites just
				throw flashy things that look cool everywhere with no real purpose, and
				somehow get a lot of points.
			</li>
			<li>
				Our site uses a framework and a build system. Most other sites likely
				won't; this is inacurate of what people might experience in the "real
				world" as basically all large companies' websites are bundled, and use a
				framework/library like React, Vue, Angular, Svelte, etc..
			</li>
			<li>We made a literal chat app.</li>
		</ul>

		<h2>Technologies Used</h2>
		<ul>
			<li>
				<a href="https://kit.svelte.dev/">SvelteKit</a> was used to make routing
				easier and to componentize everything
			</li>
			<li>
				<a href="https://tailwindcss.com/">TailwindCSS</a> and
				<a href="https://sass-lang.com">SCSS</a> was used to allow CSS to be
				written in HTML, and to allow a better DX
			</li>
			<li>
				<a href="https://threejs.org/">three.js</a> was used for the 3d models
				and 3d animation.
			</li>
		</ul>

		<p>
			A list of all the open-source licenses can be found in the
			<a href="/licenses.txt"> licenses.txt file </a>
		</p>
	</div>
</template>
